/**
 * Gauss SDK — Shared types.
 *
 * Design principles:
 *  - Every option has a sensible default
 *  - Minimal required fields — only what's truly mandatory
 *  - String unions over enums for JS-friendliness
 *  - Record<string, unknown> for extensibility
 */

// ─── Provider ──────────────────────────────────────────────────────

export type ProviderType =
  | "openai"
  | "anthropic"
  | "google"
  | "groq"
  | "ollama"
  | "deepseek"
  | "openrouter"
  | "together"
  | "fireworks"
  | "mistral"
  | "perplexity"
  | "xai";

export interface ProviderOptions {
  /** API key. Auto-resolved from environment if omitted. */
  apiKey?: string;
  baseUrl?: string;
  timeoutMs?: number;
  maxRetries?: number;
  organization?: string;
}

// ─── Messages ──────────────────────────────────────────────────────

export type MessageRole = "system" | "user" | "assistant" | "tool";

export interface Message {
  role: MessageRole;
  content: string;
}

/** @deprecated Use `Message` instead. */
export type JsMessage = Message;

// ─── Tools ─────────────────────────────────────────────────────────

export interface ToolDef {
  name: string;
  description: string;
  parameters?: Record<string, unknown>;
}

export type ToolExecutor = (callJson: string) => Promise<string>;
export type StreamCallback = (eventJson: string) => void;

// ─── Agent ─────────────────────────────────────────────────────────

export interface AgentOptions {
  instructions?: string;
  maxSteps?: number;
  temperature?: number;
  topP?: number;
  maxTokens?: number;
  seed?: number;
  stopOnTool?: string;
  outputSchema?: Record<string, unknown>;
  thinkingBudget?: number;
  /** Reasoning effort for OpenAI o-series models: "low", "medium", or "high". */
  reasoningEffort?: "low" | "medium" | "high";
  cacheControl?: boolean;
  codeExecution?: CodeExecutionOptions;
  /** Enable Google Search grounding (Gemini only). */
  grounding?: boolean;
  /** Enable native code execution / Gemini code interpreter. */
  nativeCodeExecution?: boolean;
  /** Response modalities (e.g. ["TEXT", "IMAGE"] for Gemini image generation). */
  responseModalities?: string[];
}

/** A citation reference from document-aware responses. */
export interface Citation {
  /** Citation type: char_location, page_location, content_block_location. */
  type: string;
  /** The cited text from the document. */
  citedText?: string;
  /** Title of the source document. */
  documentTitle?: string;
  /** Start index (character, page, or block depending on type). */
  start?: number;
  /** End index (character, page, or block depending on type). */
  end?: number;
}

export interface AgentResult {
  text: string;
  steps: number;
  inputTokens: number;
  outputTokens: number;
  structuredOutput?: Record<string, unknown>;
  /** Extended thinking output (Anthropic). */
  thinking?: string;
  /** Citations from document-aware responses (Anthropic). */
  citations?: Citation[];
  /** Grounding metadata from Google Search grounding. */
  groundingMetadata?: GroundingMetadata[];
}

// ─── Grounding ──────────────────────────────────────────────────────

/** Metadata from Google Search grounding. */
export interface GroundingMetadata {
  /** Search queries generated by the model. */
  searchQueries: string[];
  /** Grounding chunks (web results). */
  groundingChunks: GroundingChunk[];
  /** Rendered HTML search entry point widget. */
  searchEntryPoint?: string;
}

/** A single grounding chunk (web search result). */
export interface GroundingChunk {
  /** URL of the web result. */
  url?: string;
  /** Title of the web result. */
  title?: string;
}

// ─── Image Generation ───────────────────────────────────────────────

/** Configuration for image generation. */
export interface ImageGenerationConfig {
  /** Image model (e.g. "dall-e-3", "gemini-2.0-flash"). */
  model?: string;
  /** Desired size (e.g. "1024x1024"). */
  size?: string;
  /** Quality level (e.g. "standard", "hd"). */
  quality?: string;
  /** Style (e.g. "vivid", "natural"). */
  style?: string;
  /** Aspect ratio for Gemini (e.g. "16:9", "1:1"). */
  aspectRatio?: string;
  /** Number of images to generate. */
  n?: number;
  /** Response format ("url" or "b64_json"). */
  responseFormat?: string;
}

/** Result of image generation. */
export interface ImageGenerationResult {
  /** Generated images. */
  images: GeneratedImageData[];
  /** Revised prompt (DALL-E 3 rewrites prompts). */
  revisedPrompt?: string;
}

/** A single generated image. */
export interface GeneratedImageData {
  /** URL to the generated image (temporary). */
  url?: string;
  /** Base64-encoded image data. */
  base64?: string;
  /** MIME type. */
  mimeType?: string;
}

// ─── Provider Capabilities ──────────────────────────────────────────

/** Feature capabilities of a provider/model combination. */
export interface ProviderCapabilities {
  streaming: boolean;
  toolUse: boolean;
  vision: boolean;
  audio: boolean;
  extendedThinking: boolean;
  citations: boolean;
  cacheControl: boolean;
  structuredOutput: boolean;
  reasoningEffort: boolean;
  imageGeneration: boolean;
  grounding: boolean;
  codeExecution: boolean;
  webSearch: boolean;
}

export interface CostEstimate {
  model: string;
  normalizedModel: string;
  currency: string;
  inputTokens: number;
  outputTokens: number;
  reasoningTokens: number;
  cacheReadTokens: number;
  cacheCreationTokens: number;
  inputCostUsd: number;
  outputCostUsd: number;
  reasoningCostUsd: number;
  cacheReadCostUsd: number;
  cacheCreationCostUsd: number;
  totalCostUsd: number;
}

// ─── Code Execution (PTC) ──────────────────────────────────────────

/** Configuration for programmatic code execution runtimes. */
export interface CodeExecutionOptions {
  /** Enable Python runtime (default: true). */
  python?: boolean;
  /** Enable JavaScript/Node.js runtime (default: true). */
  javascript?: boolean;
  /** Enable Bash runtime (default: true). */
  bash?: boolean;
  /** Timeout in seconds per execution (default: 30). */
  timeoutSecs?: number;
  /** Working directory for subprocesses. */
  workingDir?: string;
  /** Sandbox mode: "default" | "strict" | "permissive" (default: "default"). */
  sandbox?: "default" | "strict" | "permissive";
  /** Use a single unified execute_code tool instead of per-language tools. */
  unified?: boolean;
}

/** Result of a code execution. */
export interface CodeExecutionResult {
  stdout: string;
  stderr: string;
  exitCode: number;
  timedOut: boolean;
  runtime: string;
  success: boolean;
}

// ─── Memory ────────────────────────────────────────────────────────

export type MemoryEntryType = "conversation" | "fact" | "preference" | "task" | "summary";
export type MemoryTier = "core" | "active" | "background" | "archive";

export interface MemoryEntry {
  id: string;
  content: string;
  entryType: MemoryEntryType;
  timestamp: string;
  tier?: MemoryTier;
  metadata?: Record<string, unknown>;
  importance?: number;
  sessionId?: string;
  embedding?: number[];
}

export interface RecallOptions {
  sessionId?: string;
  limit?: number;
}

export interface MemoryStats {
  totalEntries: number;
  [key: string]: unknown;
}

// ─── RAG / Vector Store ────────────────────────────────────────────

export interface VectorChunk {
  id: string;
  documentId: string;
  content: string;
  index: number;
  metadata?: Record<string, unknown>;
  embedding?: number[];
}

export interface SearchResult {
  id: string;
  text: string;
  score: number;
  metadata?: Record<string, unknown>;
}

// ─── Guardrails ────────────────────────────────────────────────────

export type PiiAction = "block" | "warn" | "redact";

// ─── Tool Validator ────────────────────────────────────────────────

export type CoercionStrategy =
  | "null_to_default"
  | "type_cast"
  | "json_parse"
  | "strip_null";

// ─── Eval ──────────────────────────────────────────────────────────

export type EvalScorerType = "exact_match" | "contains" | "length_ratio";

// ─── Core ──────────────────────────────────────────────────────────

/** Opaque handle returned by NAPI resource constructors. */
export type Handle = number;

/** Any SDK resource that owns native memory. */
export interface Disposable {
  destroy(): void;
}

// ─── Environment helpers ───────────────────────────────────────────

import { PROVIDER_DEFAULTS } from "./models.js";

const ENV_KEYS: Record<string, string> = {
  openai: "OPENAI_API_KEY",
  anthropic: "ANTHROPIC_API_KEY",
  google: "GOOGLE_API_KEY",
  groq: "GROQ_API_KEY",
  deepseek: "DEEPSEEK_API_KEY",
  openrouter: "OPENROUTER_API_KEY",
  together: "TOGETHER_API_KEY",
  fireworks: "FIREWORKS_API_KEY",
  mistral: "MISTRAL_API_KEY",
  perplexity: "PERPLEXITY_API_KEY",
  xai: "XAI_API_KEY",
  ollama: "",
};

/** Resolve an API key from environment for the given provider. */
export function resolveApiKey(provider: ProviderType): string {
  const key = ENV_KEYS[provider] ?? "";
  if (!key) return ""; // ollama doesn't need a key
  return (typeof process !== "undefined" ? process.env[key] : "") ?? "";
}

/** Auto-detect the best available provider from environment variables. */
export function detectProvider(): { provider: ProviderType; model: string } | undefined {
  const checks: Array<{ env: string; provider: ProviderType }> = [
    { env: "OPENAI_API_KEY", provider: "openai" },
    { env: "ANTHROPIC_API_KEY", provider: "anthropic" },
    { env: "GOOGLE_API_KEY", provider: "google" },
    { env: "GROQ_API_KEY", provider: "groq" },
    { env: "DEEPSEEK_API_KEY", provider: "deepseek" },
    { env: "OPENROUTER_API_KEY", provider: "openrouter" },
    { env: "TOGETHER_API_KEY", provider: "together" },
    { env: "FIREWORKS_API_KEY", provider: "fireworks" },
    { env: "MISTRAL_API_KEY", provider: "mistral" },
    { env: "PERPLEXITY_API_KEY", provider: "perplexity" },
    { env: "XAI_API_KEY", provider: "xai" },
  ];
  for (const { env, provider } of checks) {
    if (typeof process !== "undefined" && process.env[env]) {
      return { provider, model: PROVIDER_DEFAULTS[provider] };
    }
  }
  return undefined;
}
